### ISSUE TITLE
Error when running on Heroku

### ISSUE THREAD

**Issue by gadybadger** [evonove/django-stored-messages#13] opened 2015-06-13 06:48 UTC
I'm running django-stored-messages on Heroku in my app, and I'm running into the following error whenever any of my workers restart. Any ideas as to what could be happening here? All dependencies should be installed and configured correctly.

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/framework_django.py", 
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/messages/middleware.py", line 11, in 
    request._messages = default_storage(request)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/messages/storage/__init__.py", line 8, in 
    default_storage = lambda request: get_storage(settings.MESSAGE_STORAGE)(request)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in 
    sys.exc_info()[2])
  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in 
    module = import_module(module_path)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/stored_messages/__init__.py", line 4, in <module>
    from stored_messages.api import *
  File "/app/.heroku/python/lib/python2.7/site-packages/stored_messages/api.py", line 7, in <module>
    from stored_messages.compat import get_user_model
  File "/app/.heroku/python/lib/python2.7/site-packages/stored_messages/compat.py", line 27, in <module>
    from rest_framework.decorators import detail_route
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/decorators.py", line 11, in <module>
    from rest_framework.views import APIView
ImproperlyConfigured: Error importing module stored_messages.storage: "No module named views"
```

**Comment by gadybadger** [comment] 2015-06-13 06:55
Looks like this issue is related to how django-stored-messages interacts with Django Rest Framework. I'm running version 2.3.12 of DRF, could that be the issue?

**Comment by masci** [comment] 2015-06-14 21:44
Hi @gadybadger,
unfortunately I'm not able to reproduce your issue. I'm running stored messages + DRF 2.3.12 on Django 1.8 with Python3 but everything seems ok. Could you post some more details about your application environment?

**Comment by gadybadger** [comment] 2015-06-15 20:23
Hi @masci,
Thanks for looking into this. Here is what I'm running:
Django 1.6
DRF 2.3.12
Python 2.7.7

Pulling out the DRF related code in django-stored-messages fixed the issue, but I'm still not sure what caused it.

**Comment by palazzem** [comment] 2016-03-02 22:41
Hi @gadybadger ,
I'm sorry if I'm sending you a response after so much time and I'm really sorry if you didn't solve your issue.

Anyway, we don't support anymore these old versions of Django and DRF, so I must close this issue until someone can reproduce it with newer version of ``stored_messages``. Just to notify what is changed, we have the following compatibility table:
```
Python 2.7, 3.4, 3.5
Django 1.8, 1.9
Django Rest Framework >= 3.3 (only if you want to use REST endpoints)
```

You can also take a look at our [documentation][1] if you need help migrating to the latest version (I've added a [migration section][2] on docs).

Anyway, thank you for your time for describing your issue.

[1]: http://django-stored-messages.readthedocs.org/
[2]: http://django-stored-messages.readthedocs.org/en/latest/migrations.html

**Closed by palazzem** 2016-03-02 22:41 UTC
